### ISSUE TITLE
Flip horizontal or vertical, pls?

### ISSUE THREAD

**Issue by kubapl2004gmail** [TheWilley/Fruity_Dance_Sprite_Sheet_Generator#23]
Flip horizontal or vertical button, pls?

**Comment by TheWilley** [comment]
Hi! Thanks for the suggestion!

This one I also did not consider, but it's definitely good to have in any programs that handles images really. 

I'll definitely look into this, although I have no idea when it would be implemented as I'll put focus into the multiple selections suggestion first. This is because the flip button will be linked to the selection, and since I'm going to have to make some changes to the system that handles selections, implementing this button first would just mean more work afterwards.

In any case, I'll ve working on this after the selection system is done.

**Comment by TheWilley** [comment]
Solved by 723d6829bc8881b8955f1289b63cc7e0f6916397, will be merged into V2.4.0
